### ISSUE TITLE
MolochV2 Unlock button does not always unlock

### ISSUE THREAD

**Issue by burrrata** [HausDAO/pokemol-web#196]
Filled out a proposal and clicked `unlock` to unlock some DAI. Nothing happened. Waited, checked Metamask, waited... Nothing happened. 

Refreshed the page, filled out the proposal, and clicked `unlock` again and it worked. Not sure why.

Might be worth looking into.

**Comment by scottrepreneur** [comment]
This appears to be working ok now. Will re-open if spotted again.
