### ISSUE TITLE
Stuff that the classic Moloch DAO doesn't have, that would be nice to have

### ISSUE THREAD

**Issue by oovg** [HausDAO/pokemol-web#237]
Stuff that the classic Moloch DAO doesn't have, that would be nice to have (Democracy earth has these... so many platforms to view Moloch :slight_smile:
- Timestamp on the proposals
- Ragequit history
Other UX things more broadly confused about:
- Why do i have to use Daohaus to create DAOs and then view them on "pokemol"? Having two brands is confusing to me, unclear about the benefits (how does this actually improve the UX for the end users who are exploring new DAOs?)

**Comment by skuhlmann** [comment]
fixed with v2
