### ISSUE TITLE
Show altered state for proposals you have already voted on

### ISSUE THREAD

**Issue by skyminert** [HausDAO/pokemol-web#266]
When looking at Proposals in Voting Period (and other categories), it would be good to see some acknowledgement (or altered state) on the Proposals that you have already voted on.

Screen shot here: 
![image](https://user-images.githubusercontent.com/57817726/82933284-89fbf100-9f3e-11ea-9b48-896a10dd9966.png)

**Comment by oovg** [comment]
Good idea! Will add to UX initiative

**Comment by skuhlmann** [comment]
fixed with v2
