### ISSUE TITLE
weird voters view

### ISSUE THREAD

**Issue by pet3r-pan** [HausDAO/pokemol-web#300]
![image](https://user-images.githubusercontent.com/25356454/84581146-5ddade00-ae21-11ea-82a3-b34f84435df7.png)

Needs UI adjustment -> when I click to view who voted on a proposal

https://pokemol.com/dao/0x4570b4faf71e23942b8b9f934b47ccedf7540162/proposal/73

**Comment by skuhlmann** [comment]
fixed with v2
