### ISSUE TITLE
DAO Wallet - confusing message on "Sync to update the balance"

### ISSUE THREAD

**Issue by lumberg** [HausDAO/pokemol-web#318]
Discussed with Dekan. Logging here for record.

Yo Dekan - quick feedback/question about sending WETH directly to the DAO wallet in Molochv2:
1) This message is a bit confusing to me because it's not clear to me what it means to "Sync to update the balance". 
2) The second paragraph - is this telling me that I will need to submit a tribute proposal for the 2.1873 WETH balance to sync?

dekanbro:
That is confusing. To make direct deposits to the Dao the token needs to be whitelisted and the balance needs to be more than 0.
So yes you need to make a  proposal with Weth tribute but it could be for .001 Weth. Just needs to be more than 0
I've had trouble explaining this one because it is a little confusing and seems unnecessary.
After that proposal passes you can run the sync function to collect the tokens into the internal balances of the dao
So to whitelist a new token there needs to be the whitelist token proposal and a second proposal with tribute. It seems a little excessive to me but I think it's that way to make adding tokens very explicit. Any token added should be known and audited. Bad actors can sneak some weird stuff into ERC20s

Leo | Machi X:
i see. yeah hard to explain
i thought WETH was added when i launched the DAO. don't remember now
just make the WETH tribute and try that out i suppose.
and the sync function... is that on the dashboard somewhere?

dekanbro:
That's the button that's giving you the confusing message right now
It's okay we need a better way to explain that one. Maybe a diagram or something would help lol

Leo's suggestion: 
might just link to a help article after some basic next steps
Possibly something like:

Your DAO token balance is not displaying properly. To fix this:
1/2/3.

For more info, see this link [link here]
so if the 1/2/3 doesn't make sense, then they'll go to the article. if the 1/2/3 makes sense, problem solved.

![Pokemol-MachiX-Sync](https://user-images.githubusercontent.com/2413586/87821121-e0800e80-c8a1-11ea-95dc-dab3bf32c07a.png)

Machi X Pokemol link: https://pokemol.com/dao/0x016e79e9101a8eaa3e7f46d6d1c267819c09c939/

**Comment by scottrepreneur** [comment]
Thanks for the feedback here @lumberg! We're incorporating this into v2.
