### ISSUE TITLE
Proposals dashboard UI stops updating a partial way through voting period

### ISSUE THREAD

**Issue by nichanank** [HausDAO/pokemol-web#336]
This [proposals dashboard](https://pokemol.com/dao/0x7d58c962356ae66ba91b108751d67ae5d3b022fc/proposals/VotingPeriod) has been showing this countdown info for ~2 days:

![image](https://user-images.githubusercontent.com/15038946/89739217-3747c500-daa9-11ea-8e5d-6b7f18f6ddb9.png)

Refreshing did not change the countdown numbers. However, when I opened the link on incognito it reflects the correct status:

![image](https://user-images.githubusercontent.com/15038946/89739243-5c3c3800-daa9-11ea-8275-96e57ca838f7.png)

Not sure why it stopped syncing at ~14 hours left in Voting Period. May be related to #240. Clearing the cache on my browser did not fix the issue but **resetting my Metamask account did**. Not sure if this is a Metamask issue or the frontend but thought I would bring it up.

**OS**: MacOS Catalina 10.15.4
**Browser**: Brave 1.11.97

**Comment by scottrepreneur** [comment]
We haven't seen any other reports of this and seems to be related to Metamask. Please reopen if you experience this again.
